version: '2'

# volumes:
#   volume_homeassistant:

services:
  # homeassistant:
  #   build: ./homeassistant
  #   volumes:
  #     - volume_homeassistant:/config
  #   privileged: true
  #   restart: always
  #   ports: 
  #     - 80:8123
  
  watchman:
    build: ./watchman
    network_mode: host
    privileged: true
    labels: 
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
      io.balena.features.dbus: '1'
