# Base-image for python on any machine using a template variable
FROM homeassistant/raspberrypi3-homeassistant:0.95.1

# Copy new configuration to imported folder
COPY config /imported

# Override volume configuration with imported on runtime
CMD cp -a /imported/. /config && python -m homeassistant
# CMD cp -a /imported/. /config && hass --script auth --config . add cli_admin rabbu && python -m homeassistant --config /config
